### PR TITLE
Added joining, leaving and name changing messages.

### PR DESCRIPTION
**Pull request by Froopie**

### CODE REVIEW

**Comment by okayzed** [comment]
looks good, thanks! :shipit:

**Comment by Froopie** [comment]
cool

**Comment by Froopie** [comment]
Whats this

---------- Forwarded message ---------
De : Froopie <notifications@github.com>
Date: mer. 19 août 2020 à 02:48
Subject: [Froopie/rmHarmony] Run failed: pre-release - master (97e759f)
To: Froopie/rmHarmony <rmHarmony@noreply.github.com>
Cc: Ci activity <ci_activity@noreply.github.com>


Run failed for master (97e759f)

Repository: Froopie/rmHarmony
Workflow: pre-release
Duration: 16.0 seconds
Finished: 2020-08-19 01:48:44 UTC

View results <https://github.com/Froopie/rmHarmony/actions/runs/214510998>
Jobs:

   - pre-release <https://github.com/Froopie/rmHarmony/runs/1001069775>
   failed (1 annotation)

—
You are receiving this because this workflow ran on your branch.
Manage your GitHub Actions notifications here
<https://github.com/settings/notifications>.

**Comment by Froopie** [comment]
What does this mean

---------- Forwarded message ---------
De : Froopie <notifications@github.com>
Date: mer. 19 août 2020 à 02:48
Subject: [Froopie/rmHarmony] Run failed: release - master (97e759f)
To: Froopie/rmHarmony <rmHarmony@noreply.github.com>
Cc: Ci activity <ci_activity@noreply.github.com>


Run failed for master (97e759f)

Repository: Froopie/rmHarmony
Workflow: release
Duration: 16.0 seconds
Finished: 2020-08-19 01:48:44 UTC

View results <https://github.com/Froopie/rmHarmony/actions/runs/214510999>
Jobs:

   - release <https://github.com/Froopie/rmHarmony/runs/1001069777> failed
   (1 annotation)

—
You are receiving this because this workflow ran on your branch.
Manage your GitHub Actions notifications here
<https://github.com/settings/notifications>.

**Comment by okayzed** [comment]
oh... it's some stupid thing with github actions. the idea is that when you
push to master, the github server will build and release the files.i am
setting it up to only do it when a tag is pushed, but right now it is
acting on any commit.

**Pull request merged**
